### ISSUE TITLE
请问一下如何进入router.get('/github/callback', function(req, resp){})这个路由里面？

### ISSUE THREAD

**Issue by yourenA** [elevenBeans/WeVoting#2]
如题，好像外部没有动作去触发这个路由。

**Comment by elevenbeans** [comment]
进入Github 首页， Setting -> OAuth applications -> 创建你的应用 -> 在 ‘Authorization callback URL’ 里面输入对应路径。

Github 验证通过后会向这个 URL地址发出请求，你的应用就能接收到了 ：）

**Comment by yourenA** [comment]
@elevenBeans 好的，谢谢

**Comment by elevenbeans** [comment]
不客气，有问题就提 issue，有好的 idea 也可以实现出来提PR给我，共同学习进步 😊
